# Generated by Django 6.0.1 on 2026-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_number',
            field=models.IntegerField(default=0),
        ),
    ]
